TARGET_TYPE := bin
TARGET := app

LOC_INCLUDE += -I$(FIRMWARE_TOP)/db
LOC_INCLUDE += -I$(FIRMWARE_TOP)/basic

LIB_DIR += $(FIRMWARE_TOP)/db
LIB_DIR += $(FIRMWARE_TOP)/basic

LOC_LIBS += -lhi_db -lhi_basic

include $(FIRMWARE_TOP)/rule.mk
